# Generated by Django 5.0.2 on 2024-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HitMusicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.FileField(upload_to='tracks/')),
                ('track_name', models.CharField(max_length=25)),
                ('track_image', models.ImageField(upload_to='images/')),
                ('track_author', models.CharField(blank=True, max_length=25, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
